services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "${EUREKA_PORT:-8761}:8761"
    restart: unless-stopped
    networks:
      - smartstock-network

  gateway-service:
    build: ./GatewayService
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - smartstock-network

  auth-service:
    build: ./AuthService
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${DB_PORT:-5432}/${POSTGRES_DB:-smartstock}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL:-http://eureka-server:8761/eureka/}
    restart: unless-stopped
    networks:
      - smartstock-network

  product-service:
    build: ./ProductService
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${DB_PORT:-5432}/${POSTGRES_DB:-smartstock}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL:-http://eureka-server:8761/eureka/}
    restart: unless-stopped
    networks:
      - smartstock-network

  order-service:
    build: ./OrderService
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${DB_PORT:-5432}/${POSTGRES_DB:-smartstock}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL:-http://eureka-server:8761/eureka/}
    restart: unless-stopped
    networks:
      - smartstock-network

  customer-service:
    build: ./CustomerService
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${DB_PORT:-5432}/${POSTGRES_DB:-smartstock}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL:-http://eureka-server:8761/eureka/}
    restart: unless-stopped
    networks:
      - smartstock-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-smartstock}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-smartstock}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smartstock-network

networks:
  smartstock-network:
    driver: bridge

volumes:
  postgres-data: 