services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    restart: unless-stopped
    networks:
      - smartstock-network

  gateway-service:
    build: ./GatewayService
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - smartstock-network

  auth-service:
    build: ./AuthService
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smartstock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: unless-stopped
    networks:
      - smartstock-network

  product-service:
    build: ./ProductService
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smartstock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: unless-stopped
    networks:
      - smartstock-network

  order-service:
    build: ./OrderService
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smartstock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: unless-stopped
    networks:
      - smartstock-network

  customer-service:
    build: ./CustomerService
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smartstock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: unless-stopped
    networks:
      - smartstock-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=smartstock
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartstock"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smartstock-network

networks:
  smartstock-network:
    driver: bridge

volumes:
  postgres-data: 